Revert "Defer boto ecr client creation in FakeECRConnector"
This reverts commit 88c0ab3e0f8a827a0566e5805e9d9ebf6283a86a.

This introduces a problem for the test_endcustomer.py test in
zing/publishing:

  botocore.exceptions.NoRegionError: You must specify a region.

Change-Id: I70aa06193abb93f738d84c46cd3f5b9ea01e6d95